### ISSUE TITLE
Terminates after entering URL

### ISSUE THREAD

**Issue by m4r0n3** [sameera-madushan/Facebook-Video-Downloader#2]
Anyone having the same issue?

I've made a for-loop entering inputs from a text file line by line. It was running just as expected, until it suddenly stopped downloading after a couple of loops.

I cloned it again from the repository, and this time it just quits after entering the URL.

**Comment by m4r0n3** [comment]
Anyone having the same issue?

 I've made a for-loop entering inputs from a text file line by line. It was running just as expected, until it suddenly stopped downloading after a couple of loops.

I cloned it again from the repository, and this time it just quits after entering the URL.

**Comment by m4r0n3** [comment]
I tested it again, and it worked all by itself. I guess, my hardware is in the wrong here. Thanks, anyways!

**Comment by sameera-madushan** [comment]
Close the issue in GitHub repository if there is no issue.

**Comment by sameera-madushan** [comment]
![Capture](https://user-images.githubusercontent.com/55880211/77870698-bdccda00-725f-11ea-9128-3b9707b00d64.PNG)
