### ISSUE TITLE
Doesn't works with new facebook update

### ISSUE THREAD

**Issue by asimejaz14** [sameera-madushan/Facebook-Video-Downloader#5]
I used to get the video URL exactly the same way you showed, but Facebook doesn't show the video URL anymore in its new update. What's the counter for this?

**Comment by sameera-madushan** [comment]
Here's how you can get a video URL in the new facebook update.

![ezgif com-optimize](https://user-images.githubusercontent.com/55880211/94369153-ab940180-0105-11eb-8617-031716cdd3c7.gif)
